spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro_business_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: 'probusiness'
    password: '0000'
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 7200000