version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - /home/ssm/Documents/docker/pro_business_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_PASSWORD=0000
      - MYSQL_USER=probusiness
      - MYSQL_DATABASE=pro_business_db
